// Copyright 2024 Interdimensional Cable Network
// This file is part of ICN Chain.

//! Autogenerated weights for pallet_nsn_treasury
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2024-12-25
//! STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `dev`, CPU: `Generic`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// target/release/icn-node
// benchmark
// pallet
// --chain=dev
// --steps=50
// --repeat=20
// --pallet=pallet_nsn_treasury
// --extrinsic=*
// --execution=wasm
// --wasm-execution=compiled
// --output=./pallets/nsn-treasury/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions needed for pallet_nsn_treasury
pub trait WeightInfo {
	fn fund_treasury() -> Weight;
	fn approve_proposal() -> Weight;
	fn record_director_work() -> Weight;
	fn record_validator_work() -> Weight;
}

/// Weights for pallet_nsn_treasury using the Substrate node and recommended hardware.
/// NOTE: Includes estimated PoV sizes for Cumulus compatibility.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: Treasury TreasuryBalance (r:1 w:1)
	/// Proof: Treasury TreasuryBalance (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
	/// Storage: System Account (r:2 w:2)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	fn fund_treasury() -> Weight {
		// PoV size: TreasuryBalance(16) + Account(128*2) + overhead(128) = 400 bytes
		Weight::from_parts(50_000_000, 5717)
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(3))
	}

	/// Storage: Treasury TreasuryBalance (r:1 w:1)
	/// Proof: Treasury TreasuryBalance (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
	/// Storage: System Account (r:2 w:2)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	fn approve_proposal() -> Weight {
		// PoV size: TreasuryBalance(16) + Account(128*2) + overhead(128) = 400 bytes
		Weight::from_parts(60_000_000, 5717)
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(3))
	}

	/// Storage: Treasury AccumulatedContributionsMap (r:1 w:1)
	/// Proof: Treasury AccumulatedContributionsMap (max_values: None, max_size: Some(64), added: 2539, mode: MaxEncodedLen)
	fn record_director_work() -> Weight {
		// PoV size: AccumulatedContributionsMap(64) + overhead(64) = 128 bytes
		Weight::from_parts(20_000_000, 2539)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}

	/// Storage: Treasury AccumulatedContributionsMap (r:1 w:1)
	/// Proof: Treasury AccumulatedContributionsMap (max_values: None, max_size: Some(64), added: 2539, mode: MaxEncodedLen)
	fn record_validator_work() -> Weight {
		// PoV size: AccumulatedContributionsMap(64) + overhead(64) = 128 bytes
		Weight::from_parts(20_000_000, 2539)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	fn fund_treasury() -> Weight {
		Weight::from_parts(50_000_000, 5717)
	}
	fn approve_proposal() -> Weight {
		Weight::from_parts(60_000_000, 5717)
	}
	fn record_director_work() -> Weight {
		Weight::from_parts(20_000_000, 2539)
	}
	fn record_validator_work() -> Weight {
		Weight::from_parts(20_000_000, 2539)
	}
}
