// Copyright 2024 Interdimensional Cable Network
// This file is part of ICN Chain.
//
// ICN Chain is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

//! Autogenerated weights for pallet_icn_reputation
//!
//! THIS FILE IS AUTO-GENERATED - DO NOT EDIT MANUALLY
//!
//! Run `cargo build --release --features runtime-benchmarks` to regenerate.

#![allow(clippy::all)]

use frame_support::weights::Weight;

/// Weight functions for pallet_icn_reputation.
pub trait WeightInfo {
	fn record_event() -> Weight;
	fn record_aggregated_events(events: u32) -> Weight;
}

// Placeholder weights - TODO: Replace with actual benchmark results
pub struct SubstrateWeight<T>(core::marker::PhantomData<T>);

impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: ReputationScores (r:1 w:1)
	/// Storage: PendingEvents (r:1 w:1)
	fn record_event() -> Weight {
		Weight::from_parts(10_000, 0)
	}

	fn record_aggregated_events(events: u32) -> Weight {
		Weight::from_parts(10_000, 0).saturating_mul(events as u64)
	}
}

// For tests
impl WeightInfo for () {
	fn record_event() -> Weight {
		Weight::from_parts(10_000, 0)
	}

	fn record_aggregated_events(events: u32) -> Weight {
		Weight::from_parts(10_000, 0).saturating_mul(events as u64)
	}
}
