// Copyright 2024 Interdimensional Cable Network
// This file is part of ICN Chain.

//! Autogenerated weights for pallet_nsn_bft
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2024-12-25 (placeholder)
//!
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: None
//!
//! NOTE: Placeholder weights with estimated PoV sizes for Cumulus compatibility.

use frame_support::{traits::Get, weights::Weight};

/// Weight functions needed for pallet_nsn_bft.
pub trait WeightInfo {
    fn store_embeddings_hash() -> Weight;
    fn prune_old_consensus() -> Weight;
}

/// Weights for pallet_nsn_bft using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(core::marker::PhantomData<T>);

impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    /// Storage: EmbeddingsHashes (r:1 w:1)
    /// Proof: EmbeddingsHashes (max_values: None, max_size: Some(40), added: 2515, mode: MaxEncodedLen)
    /// Storage: ConsensusRounds (r:0 w:1)
    /// Proof: ConsensusRounds (max_values: None, max_size: Some(256), added: 2731, mode: MaxEncodedLen)
    /// Storage: ConsensusRoundStats (r:1 w:1)
    /// Proof: ConsensusRoundStats (max_values: Some(1), max_size: Some(32), added: 527, mode: MaxEncodedLen)
    fn store_embeddings_hash() -> Weight {
        // PoV size: EmbeddingsHashes(40) + ConsensusRoundStats(32) + overhead(128) = 200 bytes
        Weight::from_parts(25_000_000, 3042)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(3))
    }

    /// Storage: EmbeddingsHashes (r:N w:N)
    /// Proof: EmbeddingsHashes (max_values: None, max_size: Some(40), added: 2515, mode: MaxEncodedLen)
    /// Storage: ConsensusRounds (r:0 w:N)
    /// Proof: ConsensusRounds (max_values: None, max_size: Some(256), added: 2731, mode: MaxEncodedLen)
    fn prune_old_consensus() -> Weight {
        // PoV size: Depends on iteration, estimated average ~5000 bytes
        Weight::from_parts(50_000_000, 5000)
            .saturating_add(T::DbWeight::get().reads(100)) // Estimated max iteration
            .saturating_add(T::DbWeight::get().writes(200))
    }
}

// For backwards compatibility and tests
impl WeightInfo for () {
    fn store_embeddings_hash() -> Weight {
        Weight::from_parts(25_000_000, 3042)
    }

    fn prune_old_consensus() -> Weight {
        Weight::from_parts(50_000_000, 5000)
    }
}
