// Copyright 2024 Interdimensional Cable Network
// This file is part of ICN Chain.

//! Autogenerated weights for pallet_nsn_storage
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2025-12-24, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `dev-machine`, CPU: `<UNKNOWN>`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: None, DB CACHE: 1024

// Executed Command:
// target/release/icn-node
// benchmark
// pallet
// --pallet=pallet_nsn_storage
// --extrinsic=*
// --steps=50
// --repeat=20
// --output=pallets/nsn-storage/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions needed for pallet_nsn_storage.
pub trait WeightInfo {
	fn create_deal(s: u32) -> Weight;
	fn initiate_audit() -> Weight;
	fn submit_audit_proof() -> Weight;
	fn claim_rewards() -> Weight;
}

/// Weights for pallet_nsn_storage using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: PinningDeals (r:1 w:1)
	/// Proof: PinningDeals (max_values: None, max_size: Some(1024), added: 3499, mode: MaxEncodedLen)
	/// Storage: ShardAssignments (r:0 w:s)
	/// Proof: ShardAssignments (max_values: None, max_size: Some(256), added: 2731, mode: MaxEncodedLen)
	fn create_deal(s: u32) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `3499`
		// Minimum execution time: 10_000 picoseconds.
		Weight::from_parts(15_000_000, 3499)
			.saturating_add(Weight::from_parts(5_000_000, 0).saturating_mul(s as u64))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(s as u64)))
	}

	/// Storage: PendingAudits (r:0 w:1)
	/// Proof: PendingAudits (max_values: None, max_size: Some(512), added: 2987, mode: MaxEncodedLen)
	fn initiate_audit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 8_000 picoseconds.
		Weight::from_parts(10_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(1))
	}

	/// Storage: PendingAudits (r:1 w:1)
	/// Proof: PendingAudits (max_values: None, max_size: Some(512), added: 2987, mode: MaxEncodedLen)
	fn submit_audit_proof() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `100`
		//  Estimated: `2987`
		// Minimum execution time: 12_000 picoseconds.
		Weight::from_parts(15_000_000, 2987)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}

	/// Storage: PinnerRewards (r:1 w:1)
	/// Proof: PinnerRewards (max_values: None, max_size: Some(48), added: 2523, mode: MaxEncodedLen)
	/// Storage: System Account (r:2 w:2)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	fn claim_rewards() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `150`
		//  Estimated: `2523 + 5206 = 7729` (PinnerRewards + 2x Account)
		// Minimum execution time: 25_000 picoseconds.
		Weight::from_parts(30_000_000, 7729)
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(3))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	fn create_deal(s: u32) -> Weight {
		Weight::from_parts(15_000_000, 3499)
			.saturating_add(Weight::from_parts(5_000_000, 0).saturating_mul(s as u64))
			.saturating_add(Weight::from_parts(1, 0).saturating_mul(s as u64))
	}

	fn initiate_audit() -> Weight {
		Weight::from_parts(10_000_000, 0)
	}

	fn submit_audit_proof() -> Weight {
		Weight::from_parts(15_000_000, 2987)
	}

	fn claim_rewards() -> Weight {
		Weight::from_parts(30_000_000, 7729)
	}
}
