// Copyright 2024 Interdimensional Cable Network
// This file is part of ICN Chain.
//
// ICN Chain is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

//! Autogenerated weights for pallet_icn_director
//!
//! THIS FILE IS AUTO-GENERATED - DO NOT EDIT MANUALLY
//!
//! Run `cargo build --release --features runtime-benchmarks` to regenerate.

#![allow(clippy::all)]

use frame_support::weights::Weight;
use sp_runtime::traits::Get;

/// Weight functions for pallet_icn_director.
pub trait WeightInfo {
	fn submit_bft_result() -> Weight;
	fn challenge_bft_result() -> Weight;
	fn resolve_challenge() -> Weight;
}

// Placeholder weights - TODO: Replace with actual benchmark results
pub struct SubstrateWeight<T>(core::marker::PhantomData<T>);

impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: ElectedDirectors (r:1 w:0)
	/// Storage: BftResults (r:1 w:1)
	/// Storage: SlotStatuses (r:0 w:1)
	/// Storage: Cooldowns (r:0 w:5)
	fn submit_bft_result() -> Weight {
		Weight::from_parts(50_000, 0)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(7))
	}

	/// Storage: BftResults (r:1 w:0)
	/// Storage: FinalizedSlots (r:1 w:0)
	/// Storage: PendingChallenges (r:1 w:1)
	/// Storage: Stakes (r:1 w:0)
	/// Storage: SlotStatuses (r:0 w:1)
	fn challenge_bft_result() -> Weight {
		Weight::from_parts(75_000, 0)
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(2))
	}

	/// Storage: PendingChallenges (r:1 w:1)
	/// Storage: BftResults (r:1 w:0)
	/// Storage: ElectedDirectors (r:1 w:0)
	/// Storage: Stakes (r:5 w:5) - for slashing
	/// Storage: ReputationScores (r:5 w:5) - for recording events
	/// Storage: FinalizedSlots (r:0 w:1)
	/// Storage: SlotStatuses (r:0 w:1)
	fn resolve_challenge() -> Weight {
		Weight::from_parts(150_000, 0)
			.saturating_add(T::DbWeight::get().reads(13))
			.saturating_add(T::DbWeight::get().writes(13))
	}
}

// For tests
impl WeightInfo for () {
	fn submit_bft_result() -> Weight {
		Weight::from_parts(50_000, 0)
	}

	fn challenge_bft_result() -> Weight {
		Weight::from_parts(75_000, 0)
	}

	fn resolve_challenge() -> Weight {
		Weight::from_parts(150_000, 0)
	}
}
